import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail, FileText, ListChecks, Search, MessageSquare, ArrowRight, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  component: Dashboard,
});

const features = [
  { title: "Smart Email Generator", desc: "Draft professional emails in seconds.", url: "/email", icon: Mail },
  { title: "Meeting Notes Summarizer", desc: "Turn transcripts into concise notes & action items.", url: "/meetings", icon: FileText },
  { title: "AI Task Planner", desc: "Break down goals into clear, prioritized tasks.", url: "/tasks", icon: ListChecks },
  { title: "AI Research Assistant", desc: "Get structured briefings on any topic.", url: "/research", icon: Search },
  { title: "AI Chatbot", desc: "Conversational assistant for everything else.", url: "/chat", icon: MessageSquare },
];

function Dashboard() {
  return (
    <div className="mx-auto max-w-6xl space-y-8">
      <section className="rounded-2xl border bg-card p-8 shadow-sm">
        <div className="flex items-center gap-2 text-xs font-medium text-primary">
          <Sparkles className="h-3.5 w-3.5" />
          <span>Your AI workplace, in one suite</span>
        </div>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">
          Good to see you. What should we automate today?
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
          Workmate AI helps professionals draft emails, summarize meetings, plan tasks, and run quick
          research — all from one clean dashboard.
        </p>
        <div className="mt-5 flex flex-wrap gap-2">
          <Link
            to="/email"
            className="inline-flex items-center gap-1.5 rounded-lg bg-gradient-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-md transition hover:opacity-95"
          >
            Start with an email <ArrowRight className="h-3.5 w-3.5" />
          </Link>
          <Link
            to="/chat"
            className="inline-flex items-center gap-1.5 rounded-lg border bg-background px-4 py-2 text-sm font-medium transition hover:bg-accent"
          >
            Open chatbot
          </Link>
        </div>
      </section>

      <section>
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Tools
        </h2>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => (
            <Link
              key={f.url}
              to={f.url}
              className="group rounded-xl border bg-card p-5 shadow-sm transition hover:border-primary/40 hover:shadow-md"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-accent-foreground transition group-hover:bg-gradient-primary group-hover:text-primary-foreground">
                <f.icon className="h-5 w-5" />
              </div>
              <h3 className="mt-4 text-base font-semibold">{f.title}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{f.desc}</p>
              <div className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-primary">
                Open <ArrowRight className="h-3 w-3 transition group-hover:translate-x-0.5" />
              </div>
            </Link>
          ))}
        </div>
      </section>

      <section className="rounded-xl border bg-muted/40 p-4 text-xs text-muted-foreground">
        <strong className="text-foreground">Responsible AI:</strong> Outputs are generated by AI and
        may be inaccurate or incomplete. Always review and edit before sending, sharing, or acting
        on them. Do not submit confidential or regulated information.
      </section>
    </div>
  );
}
